### PR TITLE
Update .csproj and upgrade .NET Framerwork 4.7.2

### LINKED ISSUE #26: Compliance issue for CSProj files
The following issues have been found for TeklaStructuralDesigner_Toolkit\TeklaStructuralDesigner_Adapter\TeklaStructuralDesigner_Adapter.csproj
 - [ ] Project references for BHoM DLLs should not include Version, Culture, or Processor Architecture
 - [ ] Project references for 'Dimensional_oM' should be set to NOT copy local
 - [ ] Project references for BHoM DLLs should not include Version, Culture, or Processor Architecture

### PR DESCRIPTION
**Pull request by travispotterBH**
### Issues addressed by this PR

Closes #26

### CODE REVIEW

**Comment by travispotterBH** [comment]
@BHoMBot check project-compliance

**Comment by travispotterBH** [comment]
@BHoMBot fix project file ref. 11231520982

**Comment by travispotterBH** [comment]
@BHoMBot check project-compliance
@BHoMBot check copyright-compliance

**Review by FraserGreenroyd — APPROVED** [review]
File is now compliant, beautiful!

**Pull request merged**
